### PR TITLE
Conversion to python3

### PR DESCRIPTION
**Pull request by nikswap**
This should be a working python3 port.

### CODE REVIEW

**Comment by miohtama** [comment]
Would you like to take over the maintenance of the library?

**Comment by davsebamse** [comment]
Yes :-)

**Comment by miohtama** [comment]
Great! Please give you PyPi username and I'll give you admin rights there. Also if you need any help how to run tests, etc. please let me know.

**Comment by miohtama** [comment]
I contacted Arkadiusz how we should do this.

**Comment by davsebamse** [comment]
Hi

My pypi name is davsebamse

I am working getting the tests to run using python3.

On Fri, Dec 4, 2015 at 4:40 PM, Mikko Ohtamaa <notifications@github.com>
wrote:

> I contacted Arkadiusz how we should do this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awahlig/skype4py/pull/58#issuecomment-161999084>.
>



-- 
Master Wizz. David Askirk Fotel
Hvilebækvænge 32
3520 Farum
http://davsebamse.dk
Twitter: @davsebamse
Email: davsebamse@gmail.com
Skype: davsebamse
12884901877 er et primtal

**Comment by miohtama** [comment]
Thanks! Working on settings Skype4Py organization up.

**Comment by miohtama** [comment]
@davsebamse You have now admin rights here https://github.com/Skype4Py/Skype4Py - can you do the pull request there.

**Pull request closed without merging**
